### ISSUE TITLE
Console.log left in

### ISSUE THREAD

**Issue by gilesbutler** [wyattis/gridsome-plugin-seo#1]
Hey @wyattis,

Thanks for a great plugin. It looks like a console.log may have been left in by mistake?

![CleanShot 2021-04-16 at 12 18 29@2x](https://user-images.githubusercontent.com/790734/114962461-0e849480-9eae-11eb-967a-1ad2bef48223.jpg)

**Comment by wyattis** [comment]
Yes it was. Thanks!
